apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: assistx-dummy-apps-hpa
  namespace: dummyapps
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: assistx-dummy-apps
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80